
service: cars
frameworkVersion: '2'

provider:
  versionFunctions: false
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: local
  profile: deploy-local
  region: sa-east-1

plugins:
  - serverless-offline
  - serverless-dynamodb-local

functions:
  hello:
    handler: handler.hello

  uploadCsvVehicle:
    handler: src/vehicle/vehicleHandler.uploadCsv
    events:
      - http:
          method: post
          path: vehicle/upload_csv

custom:
  tableName: vehicles
  dynamodb:
    stages:
      - local
      - test
      - dev
    start:
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations

resources:

  Resources:
    ClientLicenseDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "UUID"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "UUID"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: vehicles